MVC_Curso/Controllers/API/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using MVC_Curso.DTOs;
using MVC_Curso.Models;
using System.Data.Entity;
using AutoMapper;

namespace MVC_Curso.Controllers.API
{
    public class MoviesController : ApiController
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/Movies
        public IEnumerable<MoviesDTO> GetMovies(string query = null)
        {
            //return _context.Movies
            var moviesQuery = _context.Movies
                .Include(m => m.Genre)
                .Where(m => m.NumberAvailable > 0);

            if (!string.IsNullOrWhiteSpace(query))
                moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));

            return moviesQuery
                .ToList()
                .Select(Mapper.Map<Movie, MoviesDTO>);
        }

        //GET /api/movies/1
        public IHttpActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movie == null)
                return NotFound();
            return Ok(Mapper.Map<Movie, MoviesDTO>(movie));
        }

        //POST /api/movies
        [HttpPost]
        public IHttpActionResult CreateMovie(MoviesDTO moviesDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movie = Mapper.Map<MoviesDTO, Movie>(moviesDTO);
            _context.Movies.Add(movie);
            _context.SaveChanges();

            moviesDTO.Id = movie.Id;
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), moviesDTO);
        }

        //PUT /api/movies/1
        [HttpPut]
        public IHttpActionResult UpdateMovie(int id, MoviesDTO moviesDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movieInDb == null)
                return NotFound();

            Mapper.Map(moviesDTO, movieInDb);

            _context.SaveChanges();
            return Ok();
        }

        // DELETE /api/movies/1
        [HttpDelete]
        public IHttpActionResult DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movieInDb == null)
                return NotFound();

            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();
            return Ok();
        }
    }
}

MVC_Curso/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Curso.Controllers
{
    public class RentalsController : Controller
    {
        
        public ActionResult New()
        {
            return View();
        }
    }
}

MVC_Curso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    @Html.Partial("_NavBar")

    <div class="container body-content" style="margin-top: 10px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MVC App</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC_Curso/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="navbar-brand">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @Html.ActionLink("MVC App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </div>
    <div class="collapse navbar-collapse" role="navigation" id="navbarColor03">
        <ul class="navbar-nav mr-auto active">
            <li class="nav-item"><a class="nav-link" href="@Url.Action("New", "Rentals")">Add rental </a></li>
            <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Customers")">Customers </a></li>
            <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Movies")">Movies </a></li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</div>